const mongoose = require('mongoose');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '.env') });

const connectDB = require('./db');
const Question = require('../models/Question');

/**
 * Authentic Question Bank categorized by Reading Skill & Competency Topics,
 * directly grounded in the official DepEd ARAL Program Learner Workbooks
 * (KS3 Plus, KS3 Basic, KS2 Plus, KS2 Basic).
 * 
 * Every question has exactly 4 choices (A, B, C, D) and a valid correctAnswer.
 */
const aralReadingQuestions = [
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // TOPIC 1: Context Clues & Roots (ARAL KS3 Plus W1, KS2 Plus W1-W2)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7V-Ia-1',
    competency: 'Context Clues & Structural Analysis',
    topic: 'Context Clues & Roots',
    difficulty: 'easy',
    prompt: 'In the sentence, "The verdant landscape was filled with lush green hills and blossoming plants," what does "verdant" mean?',
    choices: ['Lush and green', 'Dry and rocky', 'Dark and stormy', 'Barren and deserted'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W1',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7V-Ia-1',
    competency: 'Context Clues & Structural Analysis',
    topic: 'Context Clues & Roots',
    difficulty: 'easy',
    prompt: 'What type of context clue is used in: "Arachnophobia, or an intense fear of spiders, is very common among young children"?',
    choices: ['Definition / Restatement clue', 'Antonym clue', 'Cause and effect clue', 'Inference clue'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W1',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7V-Ia-2',
    competency: 'Context Clues & Structural Analysis',
    topic: 'Context Clues & Roots',
    difficulty: 'easy',
    prompt: 'What does the prefix "un-" mean in words like "unhappy" and "unpredictable"?',
    choices: ['Again', 'Not / opposite of', 'Before', 'Very much'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W1',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7V-Ia-2',
    competency: 'Context Clues & Structural Analysis',
    topic: 'Context Clues & Roots',
    difficulty: 'mid',
    prompt: 'Which suffix turns the verb "help" into an adjective meaning "giving or ready to give help"?',
    choices: ['-less', '-ful', '-ment', '-tion'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W1',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7V-Ia-1',
    competency: 'Context Clues & Structural Analysis',
    topic: 'Context Clues & Roots',
    difficulty: 'mid',
    prompt: 'In the sentence, "Unlike her gregarious brother who loved parties, Sarah was quiet and preferred staying alone," what does "gregarious" mean?',
    choices: ['Sociable and outgoing', 'Tired and sleepy', 'Selfish and rude', 'Studious and serious'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W1',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8V-Ib-1',
    competency: 'Context Clues & Structural Analysis',
    topic: 'Context Clues & Roots',
    difficulty: 'mid',
    prompt: 'What is the root word of "unbearable"?',
    choices: ['Bear', 'Able', 'Unbear', 'Un'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W1',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8V-Ib-1',
    competency: 'Context Clues & Structural Analysis',
    topic: 'Context Clues & Roots',
    difficulty: 'mid',
    prompt: 'In the phrase "a benevolent leader known for her compassion and generosity," the word "benevolent" means:',
    choices: ['Cruel and harsh', 'Kind and charitable', 'Strict and demanding', 'Cautious and fearful'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W1',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8V-Ib-2',
    competency: 'Context Clues & Structural Analysis',
    topic: 'Context Clues & Roots',
    difficulty: 'hard',
    prompt: 'What does the Latin root "dict" mean in words like "predict", "dictate", and "verdict"?',
    choices: ['To write', 'To speak or say', 'To see or look', 'To build'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W1',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7V-Ic-1',
    competency: 'Context Clues & Structural Analysis',
    topic: 'Context Clues & Roots',
    difficulty: 'easy',
    prompt: 'Identify the antonym clue in the sentence: "The pond was shallow near the shore, but deep toward the center."',
    choices: ['Pond', 'Shore', 'Deep', 'Center'],
    correctAnswer: 'C',
    source: 'DepEd ARAL KS3 Plus Workbook W1',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7V-Ic-2',
    competency: 'Context Clues & Structural Analysis',
    topic: 'Context Clues & Roots',
    difficulty: 'mid',
    prompt: 'Which word contains a prefix that means "wrongly" or "badly"?',
    choices: ['Misunderstand', 'Disappear', 'Inactive', 'Nonprofit'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W1',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8V-Id-1',
    competency: 'Context Clues & Structural Analysis',
    topic: 'Context Clues & Roots',
    difficulty: 'hard',
    prompt: '"The drought caused an acute scarcity of potable water; hence, villagers had to boil river water." What does "potable" mean?',
    choices: ['Boiling hot', 'Safe to drink', 'Stored in pots', 'Muddy and contaminated'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W1',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7V-Ie-1',
    competency: 'Context Clues & Structural Analysis',
    topic: 'Context Clues & Roots',
    difficulty: 'easy',
    prompt: 'What does the suffix "-less" indicate in the word "tireless"?',
    choices: ['Full of', 'Without', 'State of being', 'One who does'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W1',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8V-Ie-2',
    competency: 'Context Clues & Structural Analysis',
    topic: 'Context Clues & Roots',
    difficulty: 'hard',
    prompt: 'In the sentence, "Her transient smile vanished within seconds," what does "transient" mean?',
    choices: ['Lasting for a long time', 'Passing quickly / temporary', 'Bright and colorful', 'Fake and forced'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W1',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7V-If-1',
    competency: 'Context Clues & Structural Analysis',
    topic: 'Context Clues & Roots',
    difficulty: 'mid',
    prompt: 'What does the prefix "re-" mean in the word "rebuild"?',
    choices: ['Never', 'Before', 'Again', 'Under'],
    correctAnswer: 'C',
    source: 'DepEd ARAL KS3 Plus Workbook W1',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8V-If-2',
    competency: 'Context Clues & Structural Analysis',
    topic: 'Context Clues & Roots',
    difficulty: 'mid',
    prompt: 'In the sentence, "The artisan crafted intricate patterns on the wooden chest," what does "intricate" mean?',
    choices: ['Simple and plain', 'Complicated and detailed', 'Rough and broken', 'Cheap and fragile'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W1',
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // TOPIC 2: Literal vs. Implied Meaning (ARAL KS3 Plus W2)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7LT-IIa-1',
    competency: 'Literal vs. Implied Meaning',
    topic: 'Literal vs. Implied Meaning',
    difficulty: 'easy',
    prompt: 'What is the literal meaning of the word "snake"?',
    choices: ['A legless reptile that crawls on the ground', 'A deceitful or treacherous person', 'A sneaky secret', 'A sharp bend on a road'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W2',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7LT-IIa-2',
    competency: 'Literal vs. Implied Meaning',
    topic: 'Literal vs. Implied Meaning',
    difficulty: 'easy',
    prompt: 'Which sentence uses the word "home" with an implied emotional connotation rather than just a physical building?',
    choices: ['The construction workers built a home on the corner.', 'Home is where love, safety, and warmth reside.', 'The brick home has three bedrooms.', 'They painted the exterior of their home blue.'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W2',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7LT-IIb-1',
    competency: 'Literal vs. Implied Meaning',
    topic: 'Literal vs. Implied Meaning',
    difficulty: 'mid',
    prompt: 'What figure of speech is used in: "Lenny bolted for the table like a hippopotamus jumping into a muddy river"?',
    choices: ['Metaphor', 'Simile', 'Personification', 'Hyperbole'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W2',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8LT-IIb-2',
    competency: 'Literal vs. Implied Meaning',
    topic: 'Literal vs. Implied Meaning',
    difficulty: 'mid',
    prompt: 'When someone says, "It is raining cats and dogs," what is the implied meaning?',
    choices: ['Animals are falling from the sky.', 'It is raining very heavily.', 'The weather is calm and sunny.', 'Dogs and cats are fighting outside.'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W2',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8LT-IIc-1',
    competency: 'Literal vs. Implied Meaning',
    topic: 'Literal vs. Implied Meaning',
    difficulty: 'hard',
    prompt: 'Which statement contains a hyperbole (deliberate exaggeration)?',
    choices: ['I have told you a million times to submit your assignment.', 'The teacher assigned three reading comprehension questions.', 'The alarm clock rings at 6:00 in the morning.', 'Water freezes at zero degrees Celsius.'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W2',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7LT-IIc-2',
    competency: 'Literal vs. Implied Meaning',
    topic: 'Literal vs. Implied Meaning',
    difficulty: 'easy',
    prompt: 'What does the idiom "break a leg" mean when told to a student before a stage play?',
    choices: ['Be careful not to trip', 'Good luck and perform well', 'Cancel the performance', 'Hurt the competitor'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W2',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8LT-IId-1',
    competency: 'Literal vs. Implied Meaning',
    topic: 'Literal vs. Implied Meaning',
    difficulty: 'mid',
    prompt: '"The angry wind howled through the narrow mountain pass." Which literary device gives human qualities to the wind?',
    choices: ['Personification', 'Onomatopoeia', 'Irony', 'Oxymoron'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W2',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8LT-IId-2',
    competency: 'Literal vs. Implied Meaning',
    topic: 'Literal vs. Implied Meaning',
    difficulty: 'hard',
    prompt: 'What is the implied meaning of: "The classroom was a zoo during recess"?',
    choices: ['Actual animals escaped into the classroom.', 'The room was noisy, chaotic, and energetic.', 'Students were admiring zoo creatures in cages.', 'The teacher was giving a lesson about biology.'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W2',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7LT-IIe-1',
    competency: 'Literal vs. Implied Meaning',
    topic: 'Literal vs. Implied Meaning',
    difficulty: 'mid',
    prompt: 'Which word has the most positive connotation when describing someone who saves money carefully?',
    choices: ['Thrifty', 'Stingy', 'Cheap', 'Miserly'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W2',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7LT-IIe-2',
    competency: 'Literal vs. Implied Meaning',
    topic: 'Literal vs. Implied Meaning',
    difficulty: 'easy',
    prompt: 'What is the denotation of the word "blue"?',
    choices: ['A color between green and violet in the spectrum', 'Feeling sad or depressed', 'Rare or unexpected', 'Noble and aristocratic'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W2',
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // TOPIC 3: Setting, Character & Conflict (ARAL KS3 Plus W3)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7RC-IIIa-1',
    competency: 'Elements of Narrative',
    topic: 'Setting, Character & Conflict',
    difficulty: 'easy',
    prompt: 'What element of a story refers to the time and physical location where events take place?',
    choices: ['Theme', 'Setting', 'Climax', 'Plot'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W3',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7RC-IIIa-2',
    competency: 'Elements of Narrative',
    topic: 'Setting, Character & Conflict',
    difficulty: 'mid',
    prompt: 'A fisherman struggling to steer his boat safely through a violent typhoon at sea is facing what kind of conflict?',
    choices: ['Character vs. Nature', 'Character vs. Society', 'Character vs. Self', 'Character vs. Technology'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W3',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-IIIb-1',
    competency: 'Elements of Narrative',
    topic: 'Setting, Character & Conflict',
    difficulty: 'mid',
    prompt: 'Which type of conflict is internal and takes place inside a character’s mind?',
    choices: ['Character vs. Character', 'Character vs. Society', 'Character vs. Self', 'Character vs. Nature'],
    correctAnswer: 'C',
    source: 'DepEd ARAL KS3 Plus Workbook W3',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7RC-IIIb-2',
    competency: 'Elements of Narrative',
    topic: 'Setting, Character & Conflict',
    difficulty: 'easy',
    prompt: 'What is the main character who faces the central conflict in a literary story called?',
    choices: ['Antagonist', 'Protagonist', 'Narrator', 'Foil'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W3',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-IIIc-1',
    competency: 'Elements of Narrative',
    topic: 'Setting, Character & Conflict',
    difficulty: 'mid',
    prompt: 'In a narrative plot pyramid, what is the highest point of emotional tension and the turning point of the action?',
    choices: ['Exposition', 'Rising action', 'Climax', 'Resolution'],
    correctAnswer: 'C',
    source: 'DepEd ARAL KS3 Plus Workbook W3',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7RC-IIIc-2',
    competency: 'Elements of Narrative',
    topic: 'Setting, Character & Conflict',
    difficulty: 'easy',
    prompt: 'What part of a story introduces the characters, background, and initial setting?',
    choices: ['Resolution', 'Climax', 'Exposition', 'Falling action'],
    correctAnswer: 'C',
    source: 'DepEd ARAL KS3 Plus Workbook W3',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-IIId-1',
    competency: 'Elements of Narrative',
    topic: 'Setting, Character & Conflict',
    difficulty: 'hard',
    prompt: 'A character who changes and develops significantly over the course of a story is described as:',
    choices: ['A static character', 'A dynamic character', 'A flat character', 'A stereotype'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W3',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-IIId-2',
    competency: 'Elements of Narrative',
    topic: 'Setting, Character & Conflict',
    difficulty: 'mid',
    prompt: 'When a citizen speaks out against unfair community laws, what primary conflict type is depicted?',
    choices: ['Character vs. Nature', 'Character vs. Society', 'Character vs. Supernatural', 'Character vs. Self'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W3',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7RC-IIIe-1',
    competency: 'Elements of Narrative',
    topic: 'Setting, Character & Conflict',
    difficulty: 'easy',
    prompt: 'How does the setting in the passage "Be Stunned" (pebbly Malabrigo beach and verdant highlands) affect the mood of the traveler?',
    choices: ['It evokes a sense of wonder and peaceful adventure', 'It creates intense fear and suspicion', 'It causes extreme boredom and regret', 'It creates anger toward the local fishermen'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W3',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-IIIe-2',
    competency: 'Elements of Narrative',
    topic: 'Setting, Character & Conflict',
    difficulty: 'hard',
    prompt: 'What term describes hints or clues an author gives about events that will happen later in the story?',
    choices: ['Flashback', 'Foreshadowing', 'Alliteration', 'Irony'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W3',
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // TOPIC 4: Inferences & Drawing Conclusions (ARAL KS3 Plus W4)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7RC-IVa-1',
    competency: 'Inferential Comprehension',
    topic: 'Inferences & Drawing Conclusions',
    difficulty: 'easy',
    prompt: 'What is an inference in reading comprehension?',
    choices: ['A direct word-for-word copy from the text', 'A logical conclusion based on evidence and background knowledge', 'A wild guess without text support', 'The author’s biography'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W4',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7RC-IVa-2',
    competency: 'Inferential Comprehension',
    topic: 'Inferences & Drawing Conclusions',
    difficulty: 'mid',
    prompt: 'Maria grabbed her raincoat, slipped on her rubber boots, and opened her umbrella before opening the front door. What can you infer about the weather?',
    choices: ['It is a sunny summer morning', 'It is raining outside', 'A heavy snowstorm is occurring', 'The weather is windy and dry'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W4',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-IVb-1',
    competency: 'Inferential Comprehension',
    topic: 'Inferences & Drawing Conclusions',
    difficulty: 'mid',
    prompt: 'During the family meal, Nanay and Tatay listened intently and smiled warmly while Maya and Ben talked about school. What can you conclude about the family relationship?',
    choices: ['The parents are impatient with the children', 'The family members share strong bonds of affection and support', 'The siblings are afraid to speak honestly', 'The parents are strict and unapproachable'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W4',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-IVb-2',
    competency: 'Inferential Comprehension',
    topic: 'Inferences & Drawing Conclusions',
    difficulty: 'hard',
    prompt: 'In "My Birthday Disaster", why did the clown and children laugh after the cake was ruined?',
    choices: ['They disliked the birthday child', 'They recognized that accidents can be funny and chose good humor over anger', 'They were eager to leave the party early', 'They wanted another cake from the bakery'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W4',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7RC-IVc-1',
    competency: 'Inferential Comprehension',
    topic: 'Inferences & Drawing Conclusions',
    difficulty: 'easy',
    prompt: 'Leo walked into class with drooping eyes, yawning repeatedly and rubbing his temples. What is the most reasonable prediction?',
    choices: ['Leo will stay awake and run laps', 'Leo did not get enough sleep the previous night', 'Leo won an athletic prize', 'Leo is fully prepared to take an exam'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W4',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-IVc-2',
    competency: 'Inferential Comprehension',
    topic: 'Inferences & Drawing Conclusions',
    difficulty: 'mid',
    prompt: 'Smoke billowed from the kitchen, and the loud beep of the smoke detector echoed through the hallway. What can you predict will happen next?',
    choices: ['Someone will turn on the television', 'Someone will check the kitchen and turn off the heat source', 'The family will go to sleep', 'The lights will go out'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W4',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7RC-IVd-1',
    competency: 'Inferential Comprehension',
    topic: 'Inferences & Drawing Conclusions',
    difficulty: 'mid',
    prompt: 'Which question encourages inferential comprehension rather than simple literal recall?',
    choices: ['What was the boy’s name in the story?', 'Why do you think the boy decided to tell the truth despite being afraid?', 'On what day of the week did the story occur?', 'What color was the birthday cake?'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W4',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-IVd-2',
    competency: 'Inferential Comprehension',
    topic: 'Inferences & Drawing Conclusions',
    difficulty: 'hard',
    prompt: 'The dog, Lenny, bolted for the table immediately after the balloon popped. What caused Lenny’s reaction?',
    choices: ['He smelled the chocolate cake', 'He was startled and terrified by the loud explosion of the balloon', 'The clown commanded him to jump', 'He wanted to play with the children outside'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W4',
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // TOPIC 5: Author’s Purpose & Point of View (ARAL KS3 Plus W5)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7RC-Va-1',
    competency: "Author's Craft",
    topic: "Author's Purpose & Point of View",
    difficulty: 'easy',
    prompt: 'What are the three main purposes an author has when writing a text (PIE)?',
    choices: ['To Persuade, Inform, or Entertain', 'To Predict, Illustrate, or Explain', 'To Paint, Instruct, or Examine', 'To Ponder, Inspect, or Evaluate'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W5',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7RC-Va-2',
    competency: "Author's Craft",
    topic: "Author's Purpose & Point of View",
    difficulty: 'mid',
    prompt: 'What is the author’s primary purpose in a travel essay detailing the pebbly beaches, marine sanctuaries, and rice terraces of Lobo, Batangas?',
    choices: ['To persuade people to vote for local officials', 'To inform readers about and showcase the natural attractions of Lobo', 'To warn travelers never to visit Batangas', 'To advertise a commercial airline company'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W5',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-Vb-1',
    competency: "Author's Craft",
    topic: "Author's Purpose & Point of View",
    difficulty: 'easy',
    prompt: 'A story written with pronouns like "I", "me", "my", and "we" is told from which point of view?',
    choices: ['First-person point of view', 'Second-person point of view', 'Third-person limited point of view', 'Third-person omniscient point of view'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W5',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-Vb-2',
    competency: "Author's Craft",
    topic: "Author's Purpose & Point of View",
    difficulty: 'mid',
    prompt: 'When the narrator knows and reveals the inner thoughts and emotions of all characters in the story, the perspective is:',
    choices: ['First-person narrative', 'Third-person omniscient', 'Second-person imperative', 'Third-person objective'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W5',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7RC-Vc-1',
    competency: "Author's Craft",
    topic: "Author's Purpose & Point of View",
    difficulty: 'mid',
    prompt: 'An editorial article in the school paper urging students to stop throwing plastic wrappers in the hallway is written primarily to:',
    choices: ['Entertain with funny jokes', 'Persuade students to practice proper waste disposal', 'Narrate a fictional fantasy story', 'Explain how to manufacture plastics'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W5',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-Vc-2',
    competency: "Author's Craft",
    topic: "Author's Purpose & Point of View",
    difficulty: 'hard',
    prompt: 'How does the author’s tone change from the beginning to the end of "My Birthday Disaster"?',
    choices: ['From cheerful, to shocked panic, to lighthearted amusement and gratitude', 'From sad and tearful to furious anger', 'From bored to anxious throughout', 'From indifferent to fearful'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W5',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7RC-Vd-1',
    competency: "Author's Craft",
    topic: "Author's Purpose & Point of View",
    difficulty: 'easy',
    prompt: 'Which pronoun indicates second-person point of view, often used in instructional recipes and manuals?',
    choices: ['She', 'They', 'You', 'He'],
    correctAnswer: 'C',
    source: 'DepEd ARAL KS3 Plus Workbook W5',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-Vd-2',
    competency: "Author's Craft",
    topic: "Author's Purpose & Point of View",
    difficulty: 'mid',
    prompt: 'What is the tone of the narrative "Mealtime with Family"?',
    choices: ['Critical and dismissive', 'Warm, nostalgic, and affectionate', 'Sarcastic and humorous', 'Solemn and mournful'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W5',
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // TOPIC 6: Cause and Effect (ARAL KS3 Plus W6)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7RC-VIa-1',
    competency: 'Informational Analysis',
    topic: 'Cause and Effect',
    difficulty: 'easy',
    prompt: 'Which transition word or phrase signals a cause-and-effect relationship?',
    choices: ['Consequently', 'Similarly', 'However', 'Next'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W6',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7RC-VIa-2',
    competency: 'Informational Analysis',
    topic: 'Cause and Effect',
    difficulty: 'easy',
    prompt: 'In the sentence, "Because heavy rains flooded the barangay roads, classes were suspended," what is the EFFECT?',
    choices: ['Heavy rains flooded the barangay roads', 'Classes were suspended', 'The weather was cold', 'Barangay officials were asleep'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W6',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-VIb-1',
    competency: 'Informational Analysis',
    topic: 'Cause and Effect',
    difficulty: 'mid',
    prompt: 'What natural cause explains why Malabrigo Beach in Batangas is covered with smooth pebbles instead of fine sand?',
    choices: ['Heavy rainfall during monsoons', 'Strong ocean currents pushing pebbles up from the deep seabed', 'Human construction dumping river stones', 'Volcanic eruption deposits'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W6',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-VIb-2',
    competency: 'Informational Analysis',
    topic: 'Cause and Effect',
    difficulty: 'mid',
    prompt: 'In the sentence, "The balloon popped with a loud bang; as a result, Lenny leaped into the air in terror." What is the CAUSE?',
    choices: ['Lenny leaped into the air', 'The balloon popped with a loud bang', 'The cake flew everywhere', 'The clown laughed'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W6',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7RC-VIc-1',
    competency: 'Informational Analysis',
    topic: 'Cause and Effect',
    difficulty: 'easy',
    prompt: 'Which statement identifies a cause rather than an effect?',
    choices: ['The seedlings wilted and died.', 'The gardener forgot to water the garden for two weeks.', 'The crops were harvested early.', 'The fruit basket was completely empty.'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W6',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-VIc-2',
    competency: 'Informational Analysis',
    topic: 'Cause and Effect',
    difficulty: 'hard',
    prompt: 'What was the direct consequence of Mia and Sam cooperating during their Saturday chores?',
    choices: ['Their mother scolded them for playing', 'They finished their house cleaning much faster and enjoyed snack time together', 'Their pets made a bigger mess in the living room', 'They missed lunch entirely'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W6',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7RC-VId-1',
    competency: 'Informational Analysis',
    topic: 'Cause and Effect',
    difficulty: 'mid',
    prompt: 'Choose the sentence that correctly uses the transition word "due to".',
    choices: ['Due to he studied all night, he passed.', 'The flight was cancelled due to intense thunderstorm turbulence.', 'She smiled due to she saw her mother.', 'Due to the cake was chocolate, they ate it.'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W6',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-VId-2',
    competency: 'Informational Analysis',
    topic: 'Cause and Effect',
    difficulty: 'hard',
    prompt: 'When deforestation strips mountain hillsides of trees, what is the subsequent ecological effect during typhoons?',
    choices: ['Soil erosion and catastrophic mudslides', 'Increased mineral richness in the upper soil', 'Decreased rainwater volume in rivers', 'Faster growth of agricultural crops'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W6',
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // TOPIC 7: Fact vs. Opinion (ARAL KS3 Plus W7)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7RC-VIIa-1',
    competency: 'Critical Evaluation',
    topic: 'Fact vs. Opinion',
    difficulty: 'easy',
    prompt: 'What makes a statement a verifiable FACT?',
    choices: ['It reflects a personal belief or emotional feeling', 'It can be proven true or false through objective evidence or records', 'It uses words like "best", "worst", and "beautiful"', 'Most people agree with it in a casual poll'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W7',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7RC-VIIa-2',
    competency: 'Critical Evaluation',
    topic: 'Fact vs. Opinion',
    difficulty: 'easy',
    prompt: 'Which of the following statements is a verifiable FACT?',
    choices: ['Lobo is a 4th-class municipality in Batangas.', 'Lobo is the most enjoyable town in all of the Philippines.', 'Chocolate cake is more delicious than vanilla cake.', 'Traveling by boat is far more exciting than traveling by bus.'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W7',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-VIIb-1',
    competency: 'Critical Evaluation',
    topic: 'Fact vs. Opinion',
    difficulty: 'mid',
    prompt: 'Which word in a sentence strongly signals that the statement is an OPINION?',
    choices: ['Recorded', 'Measured', 'Beautiful', 'Documented'],
    correctAnswer: 'C',
    source: 'DepEd ARAL KS3 Plus Workbook W7',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7RC-VIIb-2',
    competency: 'Critical Evaluation',
    topic: 'Fact vs. Opinion',
    difficulty: 'mid',
    prompt: 'Identify the OPINION among the following statements:',
    choices: ['The Jaybanga Rice Terraces cover approximately 30 hectares of land.', 'Batangas is a province located in Region IV-A (CALABARZON).', 'Jaybanga Rice Terraces are far superior in charm to the Banaue Rice Terraces.', 'Malabrigo Point contains a historic lighthouse built during the Spanish era.'],
    correctAnswer: 'C',
    source: 'DepEd ARAL KS3 Plus Workbook W7',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-VIIc-1',
    competency: 'Critical Evaluation',
    topic: 'Fact vs. Opinion',
    difficulty: 'hard',
    prompt: '"Dr. Jose Rizal was born in Calamba, Laguna on June 19, 1861." This statement is:',
    choices: ['A historical fact supported by official birth and baptismal records', 'A subjective personal opinion', 'An exaggeration meant to persuade', 'A propaganda claim'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W7',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7RC-VIIc-2',
    competency: 'Critical Evaluation',
    topic: 'Fact vs. Opinion',
    difficulty: 'mid',
    prompt: 'Which statement represents an OPINION about pets?',
    choices: ['Dogs are mammals with four legs and fur.', 'Lenny is a golden retriever.', 'Dogs are the friendliest and most loyal pets in the entire animal kingdom.', 'Dogs require food, water, and regular physical exercise.'],
    correctAnswer: 'C',
    source: 'DepEd ARAL KS3 Plus Workbook W7',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-VIId-1',
    competency: 'Critical Evaluation',
    topic: 'Fact vs. Opinion',
    difficulty: 'hard',
    prompt: 'Why is it essential for students to distinguish between facts and opinions when reading informational articles?',
    choices: ['To avoid reading books with opinions', 'To objectively evaluate the validity and trustworthiness of an author’s claims', 'To memorize only dates and numbers', 'To ensure that every article is completely true'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W7',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-VIId-2',
    competency: 'Critical Evaluation',
    topic: 'Fact vs. Opinion',
    difficulty: 'easy',
    prompt: 'Which sentence states a FACT about human biology?',
    choices: ['The human heart has four muscular chambers.', 'Science is the most entertaining subject in junior high school.', 'Doctors are the most admirable professionals in society.', 'Exercise is always easy and fun for everyone.'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W7',
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // TOPIC 8: Propaganda Techniques & Media Bias (ARAL KS3 Plus W7)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-VIIIa-1',
    competency: 'Propaganda & Media Literacy',
    topic: 'Propaganda Techniques',
    difficulty: 'easy',
    prompt: 'What propaganda technique urges consumers to buy a product because "everyone else is using it"?',
    choices: ['Bandwagon', 'Testimonial', 'Name-calling', 'Card stacking'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W7',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-VIIIa-2',
    competency: 'Propaganda & Media Literacy',
    topic: 'Propaganda Techniques',
    difficulty: 'mid',
    prompt: 'A commercial features a famous Olympic gold medalist promoting a brand of sports drink. What propaganda device is applied?',
    choices: ['Testimonial', 'Plain folks', 'Transfer', 'Glittering generality'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W7',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-VIIIb-1',
    competency: 'Propaganda & Media Literacy',
    topic: 'Propaganda Techniques',
    difficulty: 'mid',
    prompt: 'A political candidate dresses in simple farm clothes and eats with bare hands at a rural market to appear relatable. What device is this?',
    choices: ['Plain Folks', 'Bandwagon', 'Name-calling', 'Snob appeal'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W7',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-VIIIb-2',
    competency: 'Propaganda & Media Literacy',
    topic: 'Propaganda Techniques',
    difficulty: 'hard',
    prompt: 'An advertisement uses vague, glowing words like "freedom, supreme honor, and ultimate perfection" without giving specific facts. What is this technique?',
    choices: ['Glittering Generalities', 'Card Stacking', 'Testimonial', 'Transfer'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W7',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-VIIIc-1',
    competency: 'Propaganda & Media Literacy',
    topic: 'Propaganda Techniques',
    difficulty: 'mid',
    prompt: 'When an advertisement only presents positive points about a product while hiding all negative side effects or risks, it uses:',
    choices: ['Card Stacking', 'Plain Folks', 'Name-Calling', 'Bandwagon'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W7',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-VIIIc-2',
    competency: 'Propaganda & Media Literacy',
    topic: 'Propaganda Techniques',
    difficulty: 'easy',
    prompt: 'An advertisement calls a competing detergent "cheap, useless, and harmful to clothes." What propaganda technique is being used?',
    choices: ['Name-Calling', 'Testimonial', 'Bandwagon', 'Plain Folks'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W7',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-VIIId-1',
    competency: 'Propaganda & Media Literacy',
    topic: 'Propaganda Techniques',
    difficulty: 'hard',
    prompt: 'Showing a national flag or religious symbol behind a commercial product to associate patriotic feelings with that product is an example of:',
    choices: ['Transfer', 'Name-Calling', 'Bandwagon', 'Plain Folks'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W7',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-VIIId-2',
    competency: 'Propaganda & Media Literacy',
    topic: 'Propaganda Techniques',
    difficulty: 'mid',
    prompt: 'Why do advertisers employ propaganda techniques in commercials and social media campaigns?',
    choices: ['To impart unbiased scientific data', 'To manipulate emotions and influence consumer decisions to buy or agree', 'To teach grammar rules to learners', 'To encourage open debate without taking sides'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook W7',
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // TOPIC 9: Text Types & Structures (ARAL KS3 Plus W8)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7RC-VIIIa-1',
    competency: 'Text Analysis & Structures',
    topic: 'Text Types & Structures',
    difficulty: 'easy',
    prompt: 'A text that gives step-by-step instructions on how to bake a chocolate cake or cook chicken adobo is classified as what text type?',
    choices: ['Procedural / Instructive', 'Narrative', 'Persuasive', 'Poetry'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W8',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7RC-VIIIa-2',
    competency: 'Text Analysis & Structures',
    topic: 'Text Types & Structures',
    difficulty: 'easy',
    prompt: 'What text type tells a story with characters, a setting, and a sequence of events?',
    choices: ['Narrative', 'Expository', 'Procedural', 'Technical'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W8',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-VIIIb-1',
    competency: 'Text Analysis & Structures',
    topic: 'Text Types & Structures',
    difficulty: 'mid',
    prompt: 'Which organizational text structure explains how two concepts or items are alike and how they are different?',
    choices: ['Compare and Contrast', 'Chronological / Sequence', 'Problem and Solution', 'Cause and Effect'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W8',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-VIIIb-2',
    competency: 'Text Analysis & Structures',
    topic: 'Text Types & Structures',
    difficulty: 'mid',
    prompt: 'An informational passage outlining the issue of plastic pollution in rivers and proposing community recycling drives follows which text structure?',
    choices: ['Problem and Solution', 'Chronological order', 'Spatial description', 'Flashback'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W8',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7RC-VIIIc-1',
    competency: 'Text Analysis & Structures',
    topic: 'Text Types & Structures',
    difficulty: 'easy',
    prompt: 'Words such as "first", "next", "after that", "meanwhile", and "finally" are signal words for:',
    choices: ['Chronological / Sequential order', 'Comparison and contrast', 'Cause and effect', 'Spatial layout'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W8',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-VIIIc-2',
    competency: 'Text Analysis & Structures',
    topic: 'Text Types & Structures',
    difficulty: 'hard',
    prompt: 'What primary goal distinguishes an expository text from a persuasive text?',
    choices: ['Expository informs and explains facts neutrally, while persuasive seeks to convince the reader of a viewpoint', 'Expository uses fictional animals, while persuasive uses historical kings', 'Expository always has rhyming lines, while persuasive uses prose', 'Expository is always written in the first person'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W8',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7RC-VIIId-1',
    competency: 'Text Analysis & Structures',
    topic: 'Text Types & Structures',
    difficulty: 'mid',
    prompt: 'A passage that vividly paints a picture of Lobo’s crystal-clear waters and pebbly shore using sensory words is:',
    choices: ['Descriptive', 'Persuasive', 'Procedural', 'Dramatic'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W8',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8RC-VIIId-2',
    competency: 'Text Analysis & Structures',
    topic: 'Text Types & Structures',
    difficulty: 'hard',
    prompt: 'Which text structure uses signal words such as "likewise", "similarly", "on the other hand", and "in contrast"?',
    choices: ['Compare and Contrast', 'Problem and Solution', 'Cause and Effect', 'Chronological Order'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook W8',
  },

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // TOPIC 10: Vocabulary & Word Study (ARAL KS2 & KS3 Selections)
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7V-IXa-1',
    competency: 'Vocabulary Enrichment',
    topic: 'Vocabulary & Word Study',
    difficulty: 'easy',
    prompt: 'What word from the passage "Be Stunned" is a synonym for "peaceful haven"?',
    choices: ['Sanctuary', 'Disaster', 'Current', 'Terrace'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7V-IXa-2',
    competency: 'Vocabulary Enrichment',
    topic: 'Vocabulary & Word Study',
    difficulty: 'easy',
    prompt: 'Which word is an ANTONYM for "expansive"?',
    choices: ['Vast', 'Limited / Confined', 'Wide', 'Broad'],
    correctAnswer: 'B',
    source: 'DepEd ARAL KS3 Plus Workbook',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8V-IXb-1',
    competency: 'Vocabulary Enrichment',
    topic: 'Vocabulary & Word Study',
    difficulty: 'mid',
    prompt: 'In the birthday recount, the cake was described as "enormous". Which word has the closest meaning?',
    choices: ['Gigantic', 'Fragile', 'Stale', 'Ordinary'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8V-IXb-2',
    competency: 'Vocabulary Enrichment',
    topic: 'Vocabulary & Word Study',
    difficulty: 'mid',
    prompt: 'What does the word "aroma" mean in: "The aroma of Filipino cooking filled the kitchen"?',
    choices: ['A pleasant, appetizing smell', 'A thick cloud of smoke', 'A loud clattering sound', 'A bright visual sight'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS2 Plus Workbook',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7V-IXc-1',
    competency: 'Vocabulary Enrichment',
    topic: 'Vocabulary & Word Study',
    difficulty: 'easy',
    prompt: 'Which word is a SYNONYM for "chuckle"?',
    choices: ['Laugh quietly', 'Shout angrily', 'Weep softly', 'Run swiftly'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8V-IXc-2',
    competency: 'Vocabulary Enrichment',
    topic: 'Vocabulary & Word Study',
    difficulty: 'hard',
    prompt: 'Choose the word that best completes the sentence: "The local fishermen pledged to protect the rich marine sanctuary from ________ fishing practices."',
    choices: ['destructive', 'generous', 'verdant', 'edible'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook',
  },
  {
    subject: 'Reading',
    gradeLevel: 7,
    keyStage: 'KS3',
    competencyCode: 'EN7V-IXd-1',
    competency: 'Vocabulary Enrichment',
    topic: 'Vocabulary & Word Study',
    difficulty: 'mid',
    prompt: 'What is the meaning of the word "mishap"?',
    choices: ['An unfortunate or unlucky accident', 'A grand celebration', 'A deliberate crime', 'A planned journey'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook',
  },
  {
    subject: 'Reading',
    gradeLevel: 8,
    keyStage: 'KS3',
    competencyCode: 'EN8V-IXd-2',
    competency: 'Vocabulary Enrichment',
    topic: 'Vocabulary & Word Study',
    difficulty: 'hard',
    prompt: 'Which pair of words consists of ANTONYMS?',
    choices: ['Vibrant — Dull', 'Aroma — Scent', 'Enormous — Immense', 'Verdant — Green'],
    correctAnswer: 'A',
    source: 'DepEd ARAL KS3 Plus Workbook',
  },
];

async function seedQuestionBank() {
  await connectDB();
  console.log('🌱 Connecting and indexing ARAL Reading Question Bank...');

  // Remove existing reading questions so we have clean authentic data
  const delResult = await Question.deleteMany({ subject: 'Reading' });
  console.log(`🧹 Removed ${delResult.deletedCount} prior Reading questions.`);

  const insertResult = await Question.insertMany(aralReadingQuestions);
  console.log(`✅ Successfully seeded ${insertResult.length} authentic ARAL Reading questions!`);

  // Print summary by topic
  const summary = await Question.aggregate([
    { $match: { subject: 'Reading' } },
    { $group: { _id: '$topic', count: { $sum: 1 } } },
    { $sort: { _id: 1 } },
  ]);

  console.log('\n📊 Questions seeded per topic:');
  for (const s of summary) {
    console.log(`  • ${s._id}: ${s.count} items`);
  }

  process.exit(0);
}

seedQuestionBank().catch((err) => {
  console.error('Error seeding ARAL question bank:', err);
  process.exit(1);
});
